//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class EenScore
    {
        public int ID { get; set; }
        public string Naam { get; set; }
        public int Score { get; set; }
        public int Lengte { get; set; }
        public System.DateTime Datum { get; set; }
    }
}
